apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: oscar
  app.kubernetes.io/environment: production
  app.kubernetes.io/version: v0.2
patches:
- path: deployment_patch.yaml
  target:
    kind: Deployment
    name: oscar-deployment
- path: secret_patch.yaml
  target:
    kind: Service
    name: oscar-token
- path: ingress_patch.yaml
  target:
    kind: Ingress
    name: oscar-http
resources:
- ../base
generatorOptions:
  disableNameSuffixHash: true
replicas:
- name: oscar-deployment
  count: 2
images:
- name: quay.io/cloudflavor/oscar
  newName: quay.io/cloudflavor/oscar
  newTag: v0.2
