#:schema node_modules/wrangler/config-schema.json
name = "oscar"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[env.prd]
routes = [
    { pattern = "oscar.svc.cloudflavor.io", zone_name = "cloudflavor.io", custom_domain = true },
]
[[env.prd.unsafe.bindings]]
namespace_id = "1505"
name = "OSCAR_RATE_LIMITER"
type = "ratelimit"
simple = { limit = 100, period = 60 }
kv_namespace = [{ binding = "OSCAR_STATE", id = "1505" }]
[triggers]
crons = ["0 0 * * *"]

[env.dev.unsafe]
[[env.dev.unsafe.bindings]]
name = "OSCAR_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1506"
simple = { limit = 100, period = 60 }
kv_namespace = [{ binding = "OSCAR_STATE_DEV", id = "1506" }]

[env.prd.vars]
OSCAR_LOG_LEVEL = "info"
OSCAR_ACCESS_CONFIG_URI = "https://raw.githubusercontent.com/cloudflavor/access/main/cloudflavor.toml"

[env.stg.vars]
OSCAR_LOG_LEVEL = "debug"
OSCAR_ACCESS_CONFIG_URI = "https://raw.githubusercontent.com/cloudflavor/access/main/cloudflavor.toml"

[env.dev.vars]
OSCAR_LOG_LEVEL = "debug"
OSCAR_ACCESS_CONFIG_URI = "https://raw.githubusercontent.com/cloudflavor/access/main/cloudflavor.toml"
